enable testing lightstep
... currently still fails with
```
--- FAIL: TestLoadPluginLightstep (0.02s)
panic: interface conversion: http.http2StreamError is not http.http2writeFramer: missing method writeFrame [recovered]
        panic: interface conversion: http.http2StreamError is not http.http2writeFramer: missing method writeFrame

goroutine 11 [running]:
testing.tRunner.func1(0xc4201f8870)
        /usr/local/go-1.9.2/src/testing/testing.go:711 +0x2d2
panic(0x837680, 0xc42038a000)
        /usr/local/go-1.9.2/src/runtime/panic.go:491 +0x283
plugin.lastmoduleinit(0xc65400, 0xc42023a5d0, 0xc672e0, 0x56, 0xc56420)
        /usr/local/go-1.9.2/src/runtime/plugin.go:60 +0x438
plugin.open(0xc420014840, 0x1a, 0x0, 0x0, 0x0)
        /usr/local/go-1.9.2/src/plugin/plugin_dlopen.go:113 +0x23a
plugin.Open(0xc420014840, 0x1a, 0x2, 0xc420014840, 0x1a)
        /usr/local/go-1.9.2/src/plugin/plugin.go:31 +0x35
github.com/skipper-plugins/opentracing/vendor/github.com/zalando/skipper/tracing.LoadPlugin(0x888c93, 0x7, 0xc42030caf0, 0x3, 0x2, 0x2850828800000008, 0x5a26567a, 0xc420031f98, 0x5d1f36)
        /home/hhecker/go/src/github.com/skipper-plugins/opentracing/vendor/github.com/zalando/skipper/tracing/tracing.go:74 +0x17a
github.com/skipper-plugins/opentracing.TestLoadPluginLightstep(0xc4201f8870)
        /home/hhecker/go/src/github.com/skipper-plugins/opentracing/plugin_test.go:24 +0x9d
testing.tRunner(0xc4201f8870, 0x89c838)
        /usr/local/go-1.9.2/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
        /usr/local/go-1.9.2/src/testing/testing.go:789 +0x2de
exit status 2
FAIL    github.com/skipper-plugins/opentracing  0.044s
```
...need to investigate why / workaround